### PR TITLE
Achilles Web Integration

### PR DESCRIPTION
**Pull request by tnovo**
As requested in #784 
Achilles Web Fully Integrated
Support for external APIs and ZIP data archives
User feedback considered …
Final adjustments to interface
In need of exhaustive testing and another eyes to look

Ready for release

### CODE REVIEW

**Comment by bastiao** [comment]
@tnovo can you report the status of the plugin, according to the last fixes? :)

**Comment by tnovo** [comment]
Everything ok

only needs attention on file

emif/achilles/api.py lines 102 and 313 for production. 

Can be merged :+1:

**Comment by bastiao** [comment]
@ribeiroct can you check the lines referred? we need to find a development solution because BASE_URL does not work properly for development mode.

**Comment by ribeiroct** [comment]
Yeah, im on it.

**Comment by ribeiroct** [comment]
@tnovo : 
I find the instructions very unclear, and this does not tackle some issues every deploy will have. Can you answer me some questions ? 

-First of all, where is the path for the new plugin ? It is clearly not included by default anywhere.
- How does this PR handles the importing of the plugin in a already running system ?
- How does this PR handles the importing of the plugin in a new system deploy ?

I will meanwhile keep looking for the plugin, as I am trying to merge this against the new communities branch, but this feedback would be nice.

**Comment by tnovo** [comment]
Forgot to mention that, there is an aw_conf.js that contains the configuratiion of the plugin to be added by the plugin SDK

**Comment by ribeiroct** [comment]
There should be automation of deployment procedures in the PR, as we are integrating this in our usual deployment procedures. Like the docker, and other deploys. Would be useful some kind of runnable script, data migration, or initial fixture.

**Comment by ribeiroct** [comment]
Another thing i did not mention, this PR does not include South migrations. 

I am not sure if it was explained, but could be relevant to read this here: http://www.djangopro.com/2011/01/django-database-migration-tool-south-explained/

**Comment by ribeiroct** [comment]
@tnovo : 
Would you mind changing this pull request to wip/communities2 instead of new/achilles ? I already made the necessary adjustments and is ready to merge. But i would prefer it for you to open it, since it was your work.

Just follow the link, copy paste the description of this PR, and close this one.
https://github.com/bioinformatics-ua/catalogue/compare/wip/communities2...new/achilles

**Pull request closed without merging**
