### PR TITLE
SDK icons, new methods, plugin examples and doc. revision

### PR DESCRIPTION
**Pull request by ribeiroct**
On #935 : 
- Documentation revision 

On #866 : 
- Added icon to plugin model.
- Added icons on application widgets
- Moved Applications dropdown from Databases to his own menu
- Updated PIL with the fork pillow (to support the image resize)

On #887 : 
- Ported normal tabs on fingerprint (literature, discussion and extra information) to fingerprint widget applications.
- Added container method to plugins to allow to get context DOM
container
- Added iframeresizer to live preview to improve preview visualization
- Added some widgets as examples of possibilities of the sdk.

This requires updating requirements.txt (because of change from PIL to pillow).
    
        pip install -r requirements.txt

This requires importing sdk initial data. This is done automatically on new deploys through the fixture on migrate, for currently deploys just do

    python manage.py migrate developer

### CODE REVIEW

**Comment by bastiao** [comment]
Minor issue: the link in the documentation for the plugins in github is wrong:
"""
More Examples
(...)
Please check them out here.
"""

**Comment by bastiao** [comment]
Another issue, when navigation in the databases:

```
Exception Type:	ValueError
Exception Value:	
need more than 1 value to unpack
Exception Location:	/Volumes/EXT1/Dropbox/MAPi-Dropbox/EMIF/Code/emif-fb/emif/population_characteristics/documents.py in document_form_view, line 159```

Another question: is the plugins in dev/ used by the Catalogue or it is only for demo?

**Comment by bastiao** [comment]
Another important issue: literature is not working and there is an error in that line:
```
$(".publication_details").popover({trigger: "hover", html: "true",
                template: "<div class="popover popover-small"><div class="arrow"></div><div class="popover-inner"><h3 class="popover-title"></h3><div class="popover-content"><p></p></div></div></div>"
            });

```

but only this few minor corrections and we're ready :D

**Comment by ribeiroct** [comment]
The examples are the code for the deployed versions.

The last error i think was related with #941

**Comment by bastiao** [comment]
Awesome! :+1:

**Pull request merged**
