### PR TITLE
Fixed #864:

### LINKED ISSUE #864: SDK: capability to upload a set of dependencies.
For instance a zip with a set of javascript, and css to reference in extralib, extracss.

### PR DESCRIPTION
**Pull request by ribeiroct**
Fixed #864:
- Added a versioned resource manager for each plugin version.

This needs a data migration on developer app:

    python manage.py migrate developer

### CODE REVIEW

**Comment by tnovo** [comment]
Local Resources Manager (the blue icon that allows adding dependencies) is only available after first save and refresh

Tested on Google Chrome Versão 42.0.2311.90 m (64-bit) Windows 8.1

**Comment by tnovo** [comment]
Also, zip files are not extracted

**Comment by ribeiroct** [comment]
- Yes because the version doesn't exist until you save it for the first time. It's by design, not a bug.
- They must be actual zip files, not rar or tar files.

**Comment by bastiao** [comment]
@ribeiroct is it ready to test after revisions?

**Pull request merged**
